# NumPy Tutorial: Complete Guide

## 1. Introduction to NumPy

**What is NumPy?**
- Numerical python library for array operations and numerical computing.
- Backbone for libraries like TensorFlow, PyTorch, scikit-learn.

**Installation**
bash
pip install numpy


**Importing**

import numpy as np


## 2. NumPy Arrays

In [25]:
## Creation
import numpy as np
print(np.array([1, 2, 3]))
print(np.zeros((2, 3)))
print(np.ones((3, 3)))
print(np.full((2, 2), 7))
print(np.eye(3))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))


## Attributes
a = np.array([[1,2,3],[4,5,6]])
a.shape
a.ndim
a.size
a.dtype


[1 2 3]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


dtype('int64')

## 3. Indexing, Slicing & Reshaping

In [26]:

a[1, 2]
a[:, 1]
a[0:2, 1:3]
a.reshape(3, 2)
a.flatten()




array([1, 2, 3, 4, 5, 6])

## 4. Array Operations

In [27]:
## Arithmetic Operations

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
a + b
a - b
a * b
a / b
np.dot(a, b)


##Universal Functions (ufuncs)

np.sqrt(a)
np.exp(a)
np.log(a)
np.sin(a)
np.max(a)
np.sum(a, axis=0)
np.mean(a)
np.std(a)


np.float64(1.118033988749895)

## 5. Boolean Indexing and Filtering

In [28]:

a[a > 5]
a[(a > 2) & (a < 7)]
np.where(a % 2 == 0, 1, 0)


array([[0, 1],
       [0, 1]])

## 6. Broadcasting

In [29]:

a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
a + b


array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

## 7. Copy vs View

In [30]:

x = np.array([1, 2, 3])
y = x.copy()
z = x.view()


## 8. Random Module

In [31]:

np.random.seed(0)
np.random.rand(3, 2)
np.random.randn(3, 2)
# np.random.randint(1, 10, (2, 2))
np.random.shuffle(arr)


NameError: name 'arr' is not defined

## 9. Advanced Topics

In [ ]:
## Stacking

np.vstack([a, b])
np.hstack([a, b])


##Splitting

np.split(arr, 3)
np.array_split(arr, 3)


##Sorting & Searching

np.sort(arr, axis=0)
np.argsort(arr)
np.argmin(arr)
np.argmax(arr)


## 10. Linear Algebra

In [ ]:

np.linalg.inv(matrix)
np.linalg.det(matrix)
np.linalg.eig(matrix)
np.linalg.norm(vector)
np.linalg.solve(A, b)


## 11. Saving and Loading

In [ ]:

np.save('data.npy', array)
np.load('data.npy')
np.savetxt('data.csv', array, delimiter=',')
np.genfromtxt('data.csv', delimiter=',')


## 12. NumPy in Machine Learning

| Use Case               | NumPy Functionality                   |
|------------------------|----------------------------------------|
| Data Preprocessing     | `reshape()`, `astype()`, `normalize()` |
| Batch Operations       | `np.dot()`, `np.matmul()`              |
| Vectorization          | Broadcasting, slicing                  |
| Weight Initialization  | `np.random.randn()`                   |
| Performance Optimization | `ufuncs`, `vectorized operations`    |

## 13. Best Practices

- Use **vectorized operations** over loops
- Always set **random seed** for reproducibility
- Use **np.copy()** when needed to avoid memory issues
- Be cautious with **broadcasting** in high-dimensional arrays