# NumPy Tutorial: Complete Guide

## 1. Introduction to NumPy

**What is NumPy?**
- Numerical python library for array operations and numerical computing.
- Backbone for libraries like TensorFlow, PyTorch, scikit-learn.

**Installation**
bash
pip install numpy


**Importing**

import numpy as np


## 2. NumPy Arrays

In [25]:
## Creation
import numpy as np
print(np.array([1, 2, 3]))
print(np.zeros((2, 3)))
print(np.ones((3, 3)))
print(np.full((2, 2), 7))
print(np.eye(3))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))


## Attributes
a = np.array([[1,2,3],[4,5,6]])
a.shape
a.ndim
a.size
a.dtype


[1 2 3]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


dtype('int64')

## 3. Indexing, Slicing & Reshaping

In [26]:

a[1, 2]
a[:, 1]
a[0:2, 1:3]
a.reshape(3, 2)
a.flatten()




array([1, 2, 3, 4, 5, 6])

## 4. Array Operations

In [27]:
## Arithmetic Operations

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
a + b
a - b
a * b
a / b
np.dot(a, b)


##Universal Functions (ufuncs)

np.sqrt(a)
np.exp(a)
np.log(a)
np.sin(a)
np.max(a)
np.sum(a, axis=0)
np.mean(a)
np.std(a)


np.float64(1.118033988749895)

## 5. Boolean Indexing and Filtering

In [28]:

a[a > 5]
a[(a > 2) & (a < 7)]
np.where(a % 2 == 0, 1, 0)


array([[0, 1],
       [0, 1]])

## 6. Broadcasting

In [29]:

a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
a + b


array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

## 7. Copy vs View

In [30]:

x = np.array([1, 2, 3])
y = x.copy()
z = x.view()


## 8. Random Module

In [31]:

np.random.seed(0)
np.random.rand(3, 2)
np.random.randn(3, 2)
# np.random.randint(1, 10, (2, 2))
np.random.shuffle(arr)


NameError: name 'arr' is not defined

## 9. Advanced Topics

In [ ]:
## Stacking

np.vstack([a, b])
np.hstack([a, b])


##Splitting

np.split(arr, 3)
np.array_split(arr, 3)


##Sorting & Searching

np.sort(arr, axis=0)
np.argsort(arr)
np.argmin(arr)
np.argmax(arr)


## 10. Linear Algebra

In [ ]:

np.linalg.inv(matrix)
np.linalg.det(matrix)
np.linalg.eig(matrix)
np.linalg.norm(vector)
np.linalg.solve(A, b)


## 11. Saving and Loading

In [ ]:

np.save('data.npy', array)
np.load('data.npy')
np.savetxt('data.csv', array, delimiter=',')
np.genfromtxt('data.csv', delimiter=',')


## 12. NumPy in Machine Learning

| Use Case               | NumPy Functionality                   |
|------------------------|----------------------------------------|
| Data Preprocessing     | `reshape()`, `astype()`, `normalize()` |
| Batch Operations       | `np.dot()`, `np.matmul()`              |
| Vectorization          | Broadcasting, slicing                  |
| Weight Initialization  | `np.random.randn()`                   |
| Performance Optimization | `ufuncs`, `vectorized operations`    |

## 13. Best Practices

- Use **vectorized operations** over loops
- Always set **random seed** for reproducibility
- Use **np.copy()** when needed to avoid memory issues
- Be cautious with **broadcasting** in high-dimensional arrays

Alright, Suraj. Let’s take **NumPy** from the ground up and move toward advanced proficiency.

---

## **1. Theory**

**NumPy** (Numerical Python) is a **Python library** designed for high-performance numerical computations.
It provides:

* **ndarray**: A powerful n-dimensional array object (more efficient than Python lists).
* **Vectorized operations**: Eliminates explicit loops for better speed.
* **Broadcasting**: Automatic alignment of shapes during operations.
* **Mathematical functions**: Linear algebra, Fourier transforms, statistics, etc.
* **Integration** with C, C++, Fortran code.

**Why NumPy over Lists?**

* **Speed**: Implemented in C, operates on contiguous memory blocks.
* **Memory efficiency**: Fixed-type arrays use less memory.
* **Convenience**: Built-in operations for large-scale data manipulation.

---

## **2. Conceptual Understanding**

| Concept                | Explanation                                                | Example                  |
| ---------------------- | ---------------------------------------------------------- | ------------------------ |
| **ndarray**            | Core object, multi-dimensional homogeneous array.          | `np.array([1,2,3])`      |
| **Shape**              | Tuple indicating dimensions.                               | `(3,)`, `(2,3)`          |
| **dtype**              | Data type of elements.                                     | `int32`, `float64`       |
| **Slicing & Indexing** | Extracting subarrays. Supports fancy and boolean indexing. | `arr[1:3]`, `arr[arr>5]` |
| **Broadcasting**       | Automatic shape expansion during operations.               | `arr + 5`                |
| **Vectorization**      | Applying operations to arrays without loops.               | `arr1 + arr2`            |
| **Aggregation**        | Functions like `sum()`, `mean()`, `max()` across axes.     | `arr.sum(axis=0)`        |
| **Reshaping**          | Change array dimensions without changing data.             | `arr.reshape(2,3)`       |
| **Axis concept**       | Axis 0 → rows, Axis 1 → columns (in 2D).                   | `np.sum(arr, axis=1)`    |

---

## **3. Interview Questions**

**Basic**

1. What is NumPy and why is it faster than Python lists?
2. Explain `ndarray`, `shape`, and `dtype`.
3. How does slicing in NumPy differ from Python lists?

**Intermediate**
4\. Explain broadcasting with an example.
5\. How is memory handled in NumPy arrays?
6\. What is the difference between `np.copy()` and `np.view()`?

**Advanced**
7\. How does vectorization improve performance in NumPy?
8\. What is the difference between `np.array()` and `np.asarray()`?
9\. Explain the concept of strides in NumPy.

---

## **4. Answers & Explanations**

**Q1.** NumPy is faster because it is implemented in C, uses contiguous memory blocks, and avoids Python’s object overhead by working with fixed-type data arrays.

**Q4.** **Broadcasting Example**:

```python
import numpy as np
a = np.array([1, 2, 3])
b = 2
print(a + b)  # Output: [3 4 5]
```

Here, `b` is “broadcasted” to match `a`’s shape without explicit loops.

**Q6.**

* `np.copy()` → Creates a completely new independent object.
* `np.view()` → Creates a new view pointing to the same data in memory.

**Q9.** Strides define how many bytes we move in memory to go to the next element along each dimension. Optimizing strides can drastically improve performance.



Certainly, Suraj. Let’s prepare a **comprehensive, hands-on NumPy cheatsheet** covering essential functions, grouped logically from beginner to advanced usage.

---

## **NumPy Cheatsheet — From Basics to Advanced**

### **1. Importing NumPy**

```python
import numpy as np
```

---

### **2. Creating Arrays**

```python
# From Python list
a = np.array([1, 2, 3])                # 1D array
b = np.array([[1, 2], [3, 4]])         # 2D array

# Zeros, Ones, Empty
np.zeros((3, 4))                        # 3x4 array of 0s
np.ones((2, 3), dtype=int)              # 2x3 array of 1s (int type)
np.empty((2, 3))                        # uninitialized array

# Range & Spacing
np.arange(0, 10, 2)                     # [0, 2, 4, 6, 8]
np.linspace(0, 1, 5)                    # [0., 0.25, 0.5, 0.75, 1.]

# Identity
np.eye(3)                               # 3x3 identity matrix

# Random Arrays
np.random.rand(3, 2)                    # Uniform [0,1)
np.random.randn(3, 2)                   # Normal distribution
np.random.randint(0, 10, (3, 3))        # Integers [0,10)
```

---

### **3. Array Attributes**

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.shape      # (2, 3)
arr.ndim       # 2
arr.size       # 6
arr.dtype      # dtype('int64')
arr.itemsize   # bytes per element
```

---

### **4. Indexing & Slicing**

```python
arr[0, 1]       # element at row 0, col 1 → 2
arr[1]          # second row → [4 5 6]
arr[:, 1]       # second column → [2 5]
arr[0:2, 1:3]   # subarray
arr[arr > 3]    # boolean indexing
```

---

### **5. Array Operations**

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a + b           # [5 7 9]
a - b           # [-3 -3 -3]
a * b           # element-wise multiplication
a / b           # element-wise division
a ** 2          # power
np.sqrt(a)      # square root

# Broadcasting
a + 10          # [11 12 13]
```

---

### **6. Aggregation Functions**

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

np.sum(arr)                     # sum of all elements
np.sum(arr, axis=0)              # column-wise sum
np.sum(arr, axis=1)              # row-wise sum
np.mean(arr)                     # average
np.min(arr), np.max(arr)         # min, max
np.argmin(arr), np.argmax(arr)   # indices of min/max
np.std(arr)                      # standard deviation
```

---

### **7. Reshaping & Flattening**

```python
arr.reshape(3, 2)         # change shape
arr.flatten()             # 1D copy
arr.ravel()               # 1D view (no copy)
```

---

### **8. Stacking & Splitting**

```python
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np.vstack((a, b))          # vertical stack
np.hstack((a, b.T))        # horizontal stack
np.concatenate((a, a), axis=1)

np.split(a, 2, axis=0)     # split into 2 along rows
```

---

### **9. Copy vs View**

```python
x = np.array([1, 2, 3])
y = x.view()               # shares data
z = x.copy()               # independent copy
```

---

### **10. Linear Algebra**

```python
mat = np.array([[1, 2], [3, 4]])
vec = np.array([5, 6])

np.dot(mat, vec)                   # matrix-vector dot product
np.matmul(mat, mat)                # matrix-matrix multiplication
np.linalg.inv(mat)                 # inverse
np.linalg.det(mat)                 # determinant
np.linalg.eig(mat)                 # eigenvalues & eigenvectors
```

---

### **11. Advanced — Broadcasting Example**

```python
a = np.array([[1], [2], [3]])
b = np.array([4, 5, 6])
a + b
# [[5 6 7]
#  [6 7 8]
#  [7 8 9]]
```

---

### **12. Advanced — Strides & Memory Efficiency**

```python
arr = np.arange(10)
arr.strides   # tuple showing memory step sizes in bytes
```
