<h3 align="center" style="color:blue">Codebasics Python Course: Numpy Exercise</h3>

At **AtliQ**, a software service company, the **HR team** wants to understand how happy employees are with company policies and how long they've been with the company. This survey aims to help HR improve the work environment and keep employees satisfied.

**Data Structure:** Two numpy arrays capture survey results and employee details:

**Employee Details:** Contains Employee ID, Department, and Number of Years with AtliQ.

**Survey Results:** Contains Employee ID and Happiness Score (scaled 1-10).

In [1]:
import numpy as np

# Employee Details: Employee ID, Department, Number of Years with AtliQ
employee_details = np.array([
    [101, 'Sales', 3],  
    [102, 'HR', 5],    
    [103, 'IT', 2],        
    [104, 'Sales', 8],    
    [105, 'IT', 6],      
    [106, 'HR', 4],           
    [107, 'IT', 7],    
    [108, 'Sales', 1], 
    [109, 'HR', 3]          
])

# Survey Results: Employee ID, Happiness Score (1-10)
survey_results = np.array([
    [101, 8],
    [102, 10],
    [103, 9],
    [104, 6],
    [105, 7],
    [106, 8],
    [107, 9],
    [108, 5],
    [109, 7]
])


### Task 1: Merge Arrays

**Scenario:** To streamline analysis, combine the employee details with their survey results.

**Action:** Use ```np.hstack``` to horizontally stack the two arrays.

In [4]:
merged = np.hstack((employee_details, survey_results))
merged

array([['101', 'Sales', '3', '101', '8'],
       ['102', 'HR', '5', '102', '10'],
       ['103', 'IT', '2', '103', '9'],
       ['104', 'Sales', '8', '104', '6'],
       ['105', 'IT', '6', '105', '7'],
       ['106', 'HR', '4', '106', '8'],
       ['107', 'IT', '7', '107', '9'],
       ['108', 'Sales', '1', '108', '5'],
       ['109', 'HR', '3', '109', '7']], dtype='<U21')

### Task 2: Print Scores

**Scenario:** HR wants a quick view of all happiness scores to gauge overall employee sentiment.

**Action:** Display all happiness scores from the merged array.

In [7]:
# write code here
happiness_scores = merged[:, 4].astype(int)  # Extracting happiness scores
happiness_scores

array([ 8, 10,  9,  6,  7,  8,  9,  5,  7])

### Task 3: Sort Scores

**Scenario:** HR needs to identify the range of happiness scores to plan specific interventions.

**Action:** Sort and print the happiness scores in ascending order.

In [9]:
# write code here

np.sort(merged[:, 4])  # Sorting happiness scores in ascending order

array(['10', '5', '6', '7', '7', '8', '8', '9', '9'], dtype='<U21')

### Task 4: Employee Details

**Scenario:** For a meeting, HR needs a list of employees' IDs and departments without other details.

**Action:** Iterate through the array and print each employee's ID and department.

In [11]:
# write code here

for row in merged:
    print(f"ID: {row[0]}, Department: {row[1]}")

ID: 101, Department: Sales
ID: 102, Department: HR
ID: 103, Department: IT
ID: 104, Department: Sales
ID: 105, Department: IT
ID: 106, Department: HR
ID: 107, Department: IT
ID: 108, Department: Sales
ID: 109, Department: HR


### Task 5: Happiness Scores

**Scenario:** HR wants to review individual happiness scores to follow up with specific departments or employees.

**Action:** Print the happiness score alongside each employee ID from the merged array.

In [13]:
# write code here
for row in merged:
    print(f"ID: {row[0]} Happiness Score: {row[4]}")

ID: 101 Happiness Score: 8
ID: 102 Happiness Score: 10
ID: 103 Happiness Score: 9
ID: 104 Happiness Score: 6
ID: 105 Happiness Score: 7
ID: 106 Happiness Score: 8
ID: 107 Happiness Score: 9
ID: 108 Happiness Score: 5
ID: 109 Happiness Score: 7


### Task 6: Convert Scores

**Scenario:** For statistical analysis, the HR team needs the happiness scores in a consistent format.

**Action:** Convert the happiness scores to float type using ```astype(float)```.

In [15]:
merged[:,4].astype(float)

array([ 8., 10.,  9.,  6.,  7.,  8.,  9.,  5.,  7.])

### Task 7: Average Score

**Scenario:** To measure the effectiveness of current policies, HR needs the average happiness score.

**Action:** Calculate and print the average happiness score of all employees.

In [17]:
# write code here
average_happiness = np.mean(merged[:, 4].astype(float))
print(f"Average Happiness Score: {average_happiness:.2f}")

Average Happiness Score: 7.67


### Task 8: Unique Departments

**Scenario:** HR is reviewing which departments are represented in the survey to ensure all are included in future plans.

**Action:** Use ```np.unique``` to find and print all unique departments from the employee details.

In [19]:
# first print departments from all the records
all_depeartments = merged[:, 1]
print("All Departments:", all_depeartments)
# write code here

All Departments: ['Sales' 'HR' 'IT' 'Sales' 'IT' 'HR' 'IT' 'Sales' 'HR']


In [20]:
# now print unique departments

# write code here
uniqie_depeartments = np.unique(merged[:, 1])
print("Unique Departments:", uniqie_depeartments)


Unique Departments: ['HR' 'IT' 'Sales']


### Task 9: HR Happiness

**Scenario:** HR is conducting a self-assessment to understand how their own department perceives company policies.

**Action:** Calculate and print the average happiness score within the HR department.

In [22]:
# First print all the records in HR department
hr_records = merged[merged[:, 1] == 'HR']   
hr_records
# write code here

array([['102', 'HR', '5', '102', '10'],
       ['106', 'HR', '4', '106', '8'],
       ['109', 'HR', '3', '109', '7']], dtype='<U21')

In [23]:
merged[merged[:,1]=='HR'][:,4].astype(float)

array([10.,  8.,  7.])

In [25]:
# Take an average of this column using np.mean() function

# write code here
np.average(merged[merged[:,1]=='HR'][:,4].astype(float))

np.float64(8.333333333333334)