# NumPy Operations - Practical Examples
This notebook covers most commonly used operations in NumPy with examples.

In [1]:
import numpy as np

## Array Creation

In [2]:
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])
z = np.zeros((2, 3))
o = np.ones((2, 3))
f = np.full((2, 2), 7)
i = np.eye(3)
r = np.arange(0, 10, 2)
l = np.linspace(0, 1, 5)

## Array Attributes

In [3]:
a.shape, a.ndim, a.dtype, a.size, a.itemsize

((3,), 1, dtype('int64'), 3, 8)

## Reshaping and Indexing

In [4]:
arr = np.arange(6).reshape(2, 3)
arr[0, 1], arr[:, 1], arr[1, :]

(np.int64(1), array([1, 4]), array([3, 4, 5]))

## Arithmetic Operations

In [5]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
x + y, x - y, x * y, x / y, x ** 2, x % 2

(array([5, 7, 9]),
 array([-3, -3, -3]),
 array([ 4, 10, 18]),
 array([0.25, 0.4 , 0.5 ]),
 array([1, 4, 9]),
 array([1, 0, 1]))

## Statistical Operations

In [6]:
np.mean(x), np.median(x), np.std(x), np.min(x), np.max(x), np.sum(x)

(np.float64(2.0),
 np.float64(2.0),
 np.float64(0.816496580927726),
 np.int64(1),
 np.int64(3),
 np.int64(6))

## Broadcasting

In [7]:
m = np.array([[1], [2], [3]])
n = np.array([10, 20, 30])
m + n

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

## Random Number Generation

In [8]:
np.random.rand(2, 2)
np.random.randint(0, 10, (2, 3))

array([[8, 0, 9],
       [2, 7, 4]], dtype=int32)

## Linear Algebra

In [9]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
np.dot(mat1, mat2)
np.linalg.inv(mat1)
np.linalg.det(mat1)
np.linalg.eig(mat1)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

### Core NumPy Operations in ML, DL & GenAI Workflows

| Category                      | Operation                                                        | Description                             | Usage Context                                 |
| ----------------------------- | ---------------------------------------------------------------- | --------------------------------------- | --------------------------------------------- |
| **Data Manipulation**         | `np.array()`, `np.reshape()`, `np.transpose()`, `np.stack()`     | Creating, reshaping, transposing arrays | Feeding tensors to models, reshaping features |
| **Slicing & Indexing**        | `arr[rows, cols]`, `np.where()`, `np.take()`                     | Extracting features, masking labels     | Feature selection, conditional logic          |
| **Broadcasting & Arithmetic** | `+`, `-`, `*`, `/`, `**`, `arr.mean(axis=0)`                     | Element-wise ops across tensors         | Gradient calculation, layer-wise ops          |
| **Aggregation & Statistics**  | `np.mean()`, `np.std()`, `np.var()`, `np.sum()`                  | Global or axis-wise stats               | Feature normalization, loss calculation       |
| **Linear Algebra**            | `np.dot()`, `np.matmul()`, `np.linalg.inv()`, `np.linalg.norm()` | Matrix-vector ops                       | Neural net layers, optimization               |
| **Random Number Generation**  | `np.random.randn()`, `np.random.randint()`, `np.random.seed()`   | Controlled randomness                   | Weight initialization, data sampling          |
| **Boolean Logic**             | `np.any()`, `np.all()`, `arr > threshold`                        | Conditional masking                     | Filtering predictions, thresholds             |
| **Distance Metrics**          | `np.linalg.norm(a - b)`                                          | Euclidean distance                      | Clustering, similarity computation            |
| **Data Preprocessing**        | `np.unique()`, `np.bincount()`, `np.clip()`                      | Cleaning and bounding data              | Token filtering, logit bounding               |


In [11]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[:2, 1:])

[[20 30]
 [50 60]]
